### ISSUE TITLE
On prem installation - missing yum-utils package 

### ISSUE THREAD

**Issue by micromachine** [dcos-labs/terraform-ansible-dcos#17]
Hi there, when you try use this playbook on fresh centos 7 installation, you receive a error like that : 

```
fatal: [192.168.0.217]: FAILED! => {"changed": false, "cmd": "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo", "delta": "0:00:00.004238", "end": "2018-05-13 16:00:00.061159", "msg": "non-zero return code", "rc": 127, "start": "2018-05-13 16:00:00.056921", "stderr": "/bin/sh: yum-config-manager: command not found", "stderr_lines": ["/bin/sh: yum-config-manager: command not found"], "stdout": "", "stdout_lines": []}
fatal: [192.168.0.216]: FAILED! => {"changed": false, "cmd": "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo", "delta": "0:00:00.004296", "end": "2018-05-13 16:00:00.547001", "msg": "non-zero return code", "rc": 127, "start": "2018-05-13 16:00:00.542705", "stderr": "/bin/sh: yum-config-manager: command not found", "stderr_lines": ["/bin/sh: yum-config-manager: command not found"], "stdout": "", "stdout_lines": []}
```

**Solution :** 
Add in "install system utilities" task package **"yum-utils"** to instalation list, like bellow :  
```
roles/common/tasks/main.yml 
- name: install system utilities
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset
    - ntp
    - firewalld
    - dnsmasq
    - yum-utils

```
